#ให้ Spring Boot ไปหา schema.sql / data.sql แล้ว execute
#spring.sql.init.mode=always

#=== custom datasource ===

datasource1.jdbc-url=jdbc:mariadb://localhost:3306/demo
datasource1.driver-class-name=org.mariadb.jdbc.Driver
datasource1.username=root
datasource1.password=a1234
# HikariCP Connection Pool Configuration
datasource1.maximum-pool-size=3
datasource1.minimum-idle=2
datasource1.connection-timeout=30000
datasource1.auto-commit=true
datasource1.pool-name=pool1

datasource2.jdbc-url=jdbc:mariadb://localhost:3306/demo
datasource2.driver-class-name=org.mariadb.jdbc.Driver
datasource2.username=root
datasource2.password=a1234
# HikariCP Connection Pool Configuration
datasource2.maximum-pool-size=4
datasource2.minimum-idle=1
datasource2.connection-timeout=20000
datasource2.auto-commit=true
datasource2.pool-name=pool2
